### ISSUE TITLE
Remaining tasks until --verifytypes passes and `check_type_completeness.py` can be removed

### ISSUE THREAD

**Issue by jakkdl** [python-trio/trio#2734]
To get a bit of an overview of the remaining files until we hit Type Completeness :tm:

## Public API
* TypeVarTuple support - needs to be checked with pyright instead of mypy that they're correct, but mypy should be able to accept their presence.
  * not really possible to get mypy to accept their presence in my testing, we need to wait for mypy 1.7. Tracked in #2859
* [x] SocketType, see #2720 - @jakkdl 
* _core/
  * [x] _mock_clock #2740
  * [x] _run #2733 
    * [x] _generated_run #2733
  * [x] _io_epoll #2743
    * [x] _generated_io_epoll #2743
  * [x] _io_kqueue #2743
    * [x] _generated_io_kqueue #2743
  * [x] _io_windows - some work in #2763, but I would like somebody else to take over and finish.
    * [x] _generated_io_windows
  * [x] _thread_cache #2741
  * [x] _traps #2763
* [x] testing/ #2747
* _highlevel
  * [x] _socket
  * [x] _ssl_helpers
  * [x] _serve_listeners
  * [x] _open_tcp_listeners #2724
  * [x] _open_unix_stream
* [x] _ssl #2745
* [x] _subprocess
* [x] _threads
* [x] _signals #2794 (`_open_signal_receiver` is clearly exported in `trio/__init__.py`, but for some reason doesn't show up in the file list when I run `--verifytypes`)

~~Possibly more files if running with a --pythonplatform other than linux.~~

## Private or deprecated (lower priority)
May include files that should be in the above list, I didn't look through files in a fully complete way
* _core/
  * [x] _asyncgens #2735 
  * [x] _multierror #2742
  * [x] _io_common #2763
  * [x] _windows_cffi #2755
  * [x] _ki #2763 
  * [x] _wakeup_socketpair #2763
* _tools/
  * [x] _gen_exports.py #2738
* [x] _windows_pipes #2812
* [x] _wait_for_object (windows) #2755 
* testing/
  * [x] _fake_net #2763 (This file should maybe be moved to _tests/ as it's only used internally)
* [x] _subprocess_platform/waitid
* [x] various files 

## Tests
Typing the tests will check that it's possible to use the interface in a reasonable way, as well as catch any possible bugs in the tests themself of course.
* [x] trio/testing/_fake_net
* [x] trio/_core/_tests/
* [x] trio/_tests/

## docstrings
* [x] #2762 

## Cleanup
* #2877
  * [ ] Remove references to `py.typed` in the code, from when we needed to generate it on-the-fly because it wasn't statically added in the package.
  * [ ] Remove `check_type_completeness.py`, `verify_types_[windows,linux,darwin].json` and their entries in `check.sh`
  * [ ] Add `pyright --verifytypes` with multiple platforms to `check.sh`, and/or pre-commit.

**Comment by CoolCat467** [comment]
`_core/_asyncgens` in #2735

**Comment by A5rocks** [comment]
FYI if you aren't aware, members of the org can edit issue comments! (I'm just saying, it would be cool to have people edit the initial comment in addition to their comment for notifications, so @jakkdl doesn't have to edit this all the time :-)

**Comment by jakkdl** [comment]
Clarified `[_generated]_xxx` into two separate listings for `_xxx` and a subheader for `_generated_xxx`.

**Comment by jakkdl** [comment]
Note that `_multierror`, `_asyncgens`, etc were intentionally left out of my listing as they're not required for the public interface - which should be the first priority. But I'll add a second list for non-public untyped files so those files can be coordinated on as well, since we do eventually want everything typed to catch any bugs in `trio` itself.

**Comment by jakkdl** [comment]
> FYI if you aren't aware, members of the org can edit issue comments! (I'm just saying, it would be cool to have people edit the initial comment in addition to their comment for notifications, so @jakkdl doesn't have to edit this all the time :-)

Please make a comment when non-trivially editing the list though, so everybody gets a notification

**Comment by jakkdl** [comment]
Collapsed `testing/`, and added #2720 as a TODO

**Comment by jakkdl** [comment]
Ran `--verifytypes` on windows & darwin and split out files needed for those systems, where I noticed I missed a couple docstrings in #2743

**Comment by jakkdl** [comment]
Noting down two small TODOS that weren't fully addressed in #2682

* [ ] https://github.com/python-trio/trio/pull/2682#discussion_r1259097422
https://github.com/python-trio/trio/blob/d6d650f921d9fe9dec09accded23bb60b86b8336/trio/_sync.py#L108-L122

* [ ] use `typing_extensions.Buffer` in SendStream.send_all: https://github.com/python-trio/trio/pull/2682#discussion_r1251454072

**Comment by jakkdl** [comment]
Checked off a couple dozen tasks, though didn't bother linking them to PRs. Also added a task for adding `TypeVarTuple`

**Comment by jakkdl** [comment]
I've started working on SocketType, and associated tests: `test_highlevel_open_tcp_stream`, `test_highlevel_open_tcp_listeners`, `test_highlevel_socket`, `test_socket`

**Comment by A5rocks** [comment]
For what it's worth, I don't think it's completely worth our time to *completely* type tests. I can imagine there's quite some dynamism going on there :P 

I imagine everyone's got an opinion on this already, but maybe we can try just typing a few easy ones (no insane dynamic stuff) and try to get some breadth of usage going?

**Comment by TeamSpen210** [comment]
Fully dynamic stuff no, indeed the main benefit is having a lot of sample usages of all the various functions to confirm the types make sense.

**Comment by jakkdl** [comment]
> For what it's worth, I don't think it's completely worth our time to _completely_ type tests. I can imagine there's quite some dynamism going on there :P
> 
> I imagine everyone's got an opinion on this already, but maybe we can try just typing a few easy ones (no insane dynamic stuff) and try to aim for typing a breadth of usage (rather than comprehensively for every test)?

Yeah we could set up a separate set of settings for test files, or just be more lax with `type: ignore` and `Any`

**Comment by A5rocks** [comment]
Uh, well we have py.typed so I assume this issue is solely about typing the tests now, right?

**Comment by CoolCat467** [comment]
> Uh, well we have py.typed so I assume this issue is solely about typing the tests now, right?

As far as I know, this is correct, except that `_windows_pipes` was still untyped, but #2812 is fixing that now.

**Comment by jakkdl** [comment]
yeah the title of the issue is definitely a misnomer, and with the excitement of adding types dying down as we're down to just the chore of typing the test files we don't really need this issue as a tracker either (the blacklist in `pyproject.toml` achieves it in a better way).

There's some cleanup that needs to be done though, there's 27 references to `py.typed`/`py_typed` which should be possible to remove now, and if anybody does anything with #2762 then we can fully get rid of `check_type_completeness`, the json output files and directly run `pyright --verifytypes` in CI.

**Comment by A5rocks** [comment]
Bump once again to make sure this is still relevant now that test files are typed too. (thanks again!)

**Comment by jakkdl** [comment]
> There's some cleanup that needs to be done though, there's 27 references to py.typed/py_typed which should be possible to remove now, and if anybody does anything with https://github.com/python-trio/trio/pull/2762 then we can fully get rid of check_type_completeness, the json output files and directly run pyright --verifytypes in CI.

This is still the current status, I'll rename the issue.

**Comment by jakkdl** [comment]
Updated the tasks in the OP

**Comment by jakkdl** [comment]
:rocket:
