### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#299]
* [x] #298
* [x] server helpers using new `nursery.start` framework (just tcp and ssl, defer unix domain)
* [x] Deprecations for changes in 0.3.0
  * [x] #257? – done in #308 
  * [x] #136 & #284 – done in #309
    * also moving `Task`, `UnboundedQueue` into hazmat
  * [x] #68 – see #324 
  * [x] #317 (move introspection APIs into hazmat) – see #325
  * [x] #321
  * [x] #157 – see #311
  * [x] #291
  * [x] temporary backcompat for `isinstance(x, trio.socket.SocketType)`? – done in #309
* [x] Figure out resolution for https://github.com/python-trio/trio/issues/170#issuecomment-327025129 – see #326
* [x] decide whether to rename `STATUS_IGNORED` to `TASK_STATUS_IGNORED`
* [ ] think about whether we want to do anything about #328 (but this could be deferred)
* [ ] do a pass through the docs, rearranging I/O and tutorial in light of the new networking API; also #240
* [x] Release notes
  * mention that `bind` will be becoming `async` (workaround: switch to the high-level API)
* [x] mayyyybe a basic CONTRIBUTING.md (#46)?
