### ISSUE TITLE
Umbrella issue: openssl 1.1.1/TLS 1.3 support

### ISSUE THREAD

**Issue by njsmith** [python-trio/trio#817]
Right now, if you run the trio testsuite on Ubuntu 18.10, the ssl tests fail, because Ubuntu 18.10 has openssl 1.1.1.

There are several aspects to this that I'll split into separate issues:

* [x] We should test against openssl 1.1.1 in CI, so we can tell whether it's working: #818
* [x] The way openssl 1.1.1/TLS 1.3 handles session tickets causes `test_SSLStream_generic` to hang: #819
* [x] There are new constants exposed in the ssl module, causing `test_exports.py` to fail
* [x] openssl now raises `SSLZeroReturnError` in several situations where it didn't before, and we need to handle them properly
* [x] we should make sure the renegotiation tests properly limit themselves to TLS v1.2. There's some code that tries to do that, but it looks like `OpenSSL.SSL.OP_NO_TLSv1_3` is missing, so it probably doesn't work?
* [x] we should possibly run at least some of the tests with both TLS v1.2 and TLS v1.3 on openssl v1.1.1? We do automatically get some coverage of both protocols by testing on multiple openssl versions, but v1.1.1 might be different.

Also, while not required to get the test suite passing, it would be good to:

* [ ] Support early data: #223 
* [ ] Support post-handshake auth: #741

**Comment by njsmith** [comment]
All the top-line boxes here are checked off now, and the other items have their own dedicated issues, so I guess we can close this.
